name: ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAGS: luisnaldo7/eth-duties-dashboard:dev
    steps:
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "TAGS=luisnaldo7/eth-duties-dashboard:latest,luisnaldo7/eth-duties-dashboard:prod" >> "$GITHUB_ENV"  
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ env.TAGS }}
